import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import ThemeToggle from '@/components/ThemeToggle'
import '@/styles/globals.css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon_48px',
    other: [
      {
        rel: 'icon',
        type: 'image/x-icon',
        media: '(prefers-color-scheme: dark)',
        url: '/favicon_48px.svg',
      },
    ],
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <header className="p-4 bg-background border-b border-border flex justify-between">
          <ThemeToggle />
        </header>
        {children}
      </body>
    </html>
  )
}
